In [ ]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy
import random
from config import weather_api_key
from datetime import datetime
import json

In [ ]:
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs

In [ ]:
coordinates = list(lat_lngs)
coordinates

In [ ]:
cities = []

for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    if city not in cities:
        cities.append(city)

len(cities)

In [ ]:
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
url

In [ ]:
city_data = []

print("Beginning Data Retrieval     ")
print("-----------------------------")

record_count = 1
set_count = 1

for i, city in enumerate(cities):

    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
    
    city_url = url + "&q=" + city.replace(" ","+")

    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    record_count += 1
    
    try:
        city_weather = requests.get(city_url).json()
        
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_country = city_weather["sys"]["country"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        description = city_weather['weather'][0]['description']
      
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        
        city_data.append({"City": city.title(),
                          "Country": city_country,
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Current Description":description })

    except:
        print("City not found. Skipping...")
        pass

print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

In [13]:
#city_data_df = pd.DataFrame(city_data)
#city_data_df.head(10)

ci_da_df = pd.DataFrame(cities)
ci_da_df.head(10)

                        0
0                   bluff
1             tuktoyaktuk
2  grand river south east
3            punta arenas
4               ulladulla
5               busselton
6                meulaboh
7                  albany
8            ponta do sol
9                 ushuaia

In [14]:
city_data_df = pd.DataFrame(city_data)
city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Bluff,NZ,-46.6000,168.3333,52.81,83,100,9.89,overcast clouds
1,Tuktoyaktuk,CA,69.4541,-133.0374,18.86,84,18,6.49,few clouds
2,Punta Arenas,CL,-53.1500,-70.9167,48.31,61,0,16.11,clear sky
3,Ulladulla,AU,-35.3500,150.4667,58.78,84,78,4.83,broken clouds
4,Busselton,AU,-33.6500,115.3333,53.96,87,0,10.29,clear sky
...,...,...,...,...,...,...,...,...,...
703,Bastia,FR,42.6667,9.3333,60.60,89,75,2.30,broken clouds
704,Moindou,NC,-21.6924,165.6770,74.95,80,8,4.07,clear sky
705,Bay Roberts,CA,47.5999,-53.2648,35.04,73,87,5.99,overcast clouds
706,Amapa,BR,1.0000,-52.0000,75.36,96,100,3.69,overcast clouds
707,Caxito,AO,-8.5785,13.6643,75.88,99,100,3.98,heavy intensity rain

In [26]:
output_data_file = "Weather_Database/WeatherPy_Database.csv"

city_data_df.to_csv(output_data_file, index_label="City_ID")

FileNotFoundError: [Errno 2] No such file or directory: 'Weather_Database/WeatherPy_Database.csv'